version: '3.8'
services:
  db:
    container_name: postgres
    image: 'postgres:14'
    restart: always
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  api:
    container_name: api
    restart: always
    build: .
    command: ["yarn", "dev"]
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/app
    - nodemodules:/src/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT_NUMBER=${PORT}
      - DB_CLIENT=${DATABASE_CLIENT}
      - DB_USER=${DATABASE_USER}
      - DB_HOST=${DATABASE_HOST}
      - DB_NAME=${DATABASE_NAME}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_PORT=${DATABASE_PORT}

volumes: 
 data: {}
 nodemodules: {}

networks:
  brain_agriculture_network:
    external: true